# Generated by Django 2.2.7 on 2019-12-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixBackend', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='product_options',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='product_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='location_name',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='product_email',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
